### ISSUE TITLE
crosstools-ng support

### ISSUE THREAD

**Issue by nishanthkarthik** [aspect-build/gcc-toolchain#43]
Can I replace the current docker-based sysroots with the ones I generate using crosstools? I am looking for more control over glibc and libstdc++ versions.

**Comment by f0rmiga** [comment]
This is not something we can maintain right now. Maybe if you contribute, including tests, we can try to support it.

**Comment by cgrindel** [comment]
@nishanthkarthik Please reopen this issue if there is more to be discussed. Thanks!
